server:
  port: 9099                                # 项目访问端口，默认 8080
  servlet:                                 # 项目访问路径，默认 /
    context-path: /win-rpc

# Spring
spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # 指定 druid 连接池以及 druid 连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1                       # 初始连接数
      max-active: 20                        # 最大连接数
      max-idle: 20                          # 最大空闲
      min-idle: 1                           # 最小空闲
      max-wait: 60000                       # 最长等待时间
  # redis 缓存
  redis:
    timeout: 10000                          # 连接超时时间
    host: 192.168.10.100                    # Redis服务器地址
    port: 6379                              # Redis服务器端口
    database: 0                             # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024                    # 最大连接数，默认 8
        max-wait: 10000                     # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200                       # 最大空闲连接，默认 8
        min-idle: 5                         # 最小空闲连接，默认 0
    password: root
  # Dubbo
  dubbo:
    #开启dubbo服务
    server: true
    # 提供方应用信息，用于计算依赖关系
    application:
      name: rpc-provider
    # 使用 zookeeper 注册中心暴露服务地址
    registry:
      address: zookeeper://192.168.10.100:2181?backup=192.168.10.100:2182,192.168.10.100:2183
    # 用 dubbo 协议在 20880 端口暴露服务
    protocol:
      name: dubbo
      port: 20880
    # 扫描需要暴露的服务接口包
    scan:
      base-packages: com.hereWeGo.rpc.service

# MyBatis
mybatis:
  # 配置 MyBatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.hereWeGo.rpc.pojo
  # 配置 MyBatis Mapper 映射文件
  mapper-locations: classpath:mapper/*.xml

# Mybatis SQL 打印(方法接口所在的包，不是 Mapper.xml 所在的包)
logging:
  level:
    com.hereWeGo.manager.mapper: debug

# Redis Key
# 商品分类列表 Key
goods.category.list.key: goods:category:list:goodsCategoryList
#用户购物车key
user.cart: userCart

# Elasticsearch
elasticsearch:
  address: 192.168.10.100:9200, 192.168.10.100:9201, 192.168.10.100:9202


